branch-defaults:
  default:
    environment: data-drops-app
    group_suffix: null
global:
  application_name: data-drops-app
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
