/** Exact Lanvac CITY spellings from the dealer 10638 export (junk rows omitted).
 *  New accounts should use a preferred spelling. Imported accounts keep the export value.
 */

export const LANVAC_DISPATCH_CITIES = [
  "ALGONQUIN HIGHLANDS",
  "Algonquin Highlands",
  "ALGONQUIN HIGHLANDS - ON",
  "Algonquin Highlands - ON",
  "ALGONQUIN HIGHLANDS - Ontario",
  "Algonquin Highlands - Ontario",
  "ALGONQUIN HIGHLANDS ON",
  "ALGONQUIN HIGHLANDS, ON",
  "ALGONUIN HIGHLANDS",
  "APSLEY ON",
  "BANCROFT",
  "Bancroft - On",
  "Bancroft - ONTARIO",
  "BANCROFT ON",
  "BANCROFT, ON",
  "BARRIE",
  "BURNT RIVER",
  "Cardiff - ON",
  "Carnarvon",
  "CARNARVON - ON",
  "Carnarvon - ON",
  "CARNARVON ON",
  "CARNARVON, ON",
  "CARNARVON-ON",
  "COBOCONCK",
  "COBOCONK - Ontario",
  "COE HILL",
  "Combermere - ON",
  "DORSET",
  "Dorset - ON",
  "DORSET - Ontario",
  "EAGLE LAKE",
  "EAGLE LAKE - ON",
  "Eagle LAKE - ON",
  "Eagle Lake - ON",
  "EAGLE LAKE - Ontario",
  "EAGLE LAKE ON",
  "EAGLE LAKE, ON",
  "FORT IRWIN",
  "Fort Irwin - Ontario",
  "FORT IRWIN ON",
  "Gooderham - ON",
  "Gooderham - Ontario",
  "HALIBURTON",
  "Haliburton",
  "HALIBURTON  ON",
  "HALIBURTON - ON",
  "Haliburton - ON",
  "Haliburton - On",
  "Haliburton - On (ALGONQUIN HIGHLANDS)",
  "HALIBURTON - ONTARIO",
  "Haliburton - Ontario",
  "HALIBURTON ON",
  "Haliburton ON",
  "HALIBURTON ON.",
  "HALIBURTON, ON",
  "HALIBURTON, ONT",
  "HAMILTON",
  "Harcourt - ON",
  "Hers - Ontario",
  "HIGHLANDS EAST",
  "Kennisis Lake - ON",
  "KENNISIS LAKE ON",
  "KINMOUNT",
  "KINMOUNT - ON",
  "Kinmount - ON",
  "KINMOUNT ON",
  "Lindsay - On",
  "Maple Leaf - ON",
  "MINDEN",
  "Minden",
  "MINDEN - ON",
  "Minden - ON",
  "MINDEN - Ontario",
  "Minden - Ontario",
  "Minden Hills - ON",
  "MINDEN ON",
  "MINDEN ON.",
  "MINDEN, ON",
  "Nephton ON",
  "Norland - ON",
  "NORLAND ON",
  "Parry Sound - ON",
  "PETERBOROUGH",
  "Peterborough - On",
  "Port Perry - Ontario",
  "South Algonquin - ON",
  "Stouffville - ON",
  "TORY HILL - ON",
  "Trent Lakes, ON",
  "WEST GUIFORD ON.",
  "WEST GUILFORD",
  "WEST GUILFORD - ON",
  "West Guilford - ON",
  "WEST GUILFORD ON",
  "WEST GUILFORD ONT",
  "WEST GUILFORD, ON",
  "WEST GUILFPRD ON.",
  "Whitchurch - ON",
  "Wilberforce - ON",
  "WILBERFORCE ON",
] as const;

export type LanvacDispatchCity = (typeof LANVAC_DISPATCH_CITIES)[number];

/** Spellings to offer first when creating a new monitoring client. */
export const LANVAC_DISPATCH_CITIES_PREFERRED = [
  "Algonquin Highlands - ON",
  "Bancroft - On",
  "Cardiff - ON",
  "Carnarvon - ON",
  "COBOCONK - Ontario",
  "Combermere - ON",
  "Dorset - ON",
  "Eagle Lake - ON",
  "Fort Irwin - Ontario",
  "Gooderham - ON",
  "Haliburton - On",
  "Harcourt - ON",
  "HIGHLANDS EAST",
  "Kennisis Lake - ON",
  "Kinmount - ON",
  "Lindsay - On",
  "Maple Leaf - ON",
  "Minden - ON",
  "Minden Hills - ON",
  "Norland - ON",
  "Parry Sound - ON",
  "Peterborough - On",
  "South Algonquin - ON",
  "TORY HILL - ON",
  "Trent Lakes, ON",
  "West Guilford - ON",
  "Wilberforce - ON",
] as const;

const ALL = new Set<string>(LANVAC_DISPATCH_CITIES);
const PREFERRED = new Set<string>(LANVAC_DISPATCH_CITIES_PREFERRED);

export function lanvacCitySelectOptions(current?: string | null): {
  preferred: string[];
  other: string[];
  extra: string | null;
} {
  const extra = current?.trim() && !ALL.has(current.trim()) ? current.trim() : null;
  return {
    preferred: [...LANVAC_DISPATCH_CITIES_PREFERRED],
    other: LANVAC_DISPATCH_CITIES.filter((city) => !PREFERRED.has(city)),
    extra,
  };
}
